#!/bin/bash

function man2html {
   mkdir -p ~/Downloads/man2html
   for x; do
    man $x | 2>/dev/null groff -mandoc -Thtml > ~/Downloads/man2html/$x.html || return
    echo ">" ~/Downloads/man2html/$x.html
   done
}

function vi {
   vim "$@"
}

function myip {
   #curl https://ipinfo.io/ip
   curl -w "\n" ident.me
   #curl -w "\n" ifconfig.me
}

#curl wrapper
curlj ()
{
    "$@" -s | python -mjson.tool > /tmp/a.json;
    vi /tmp/a.json
}

pjson ()
{
   python -mjson.tool
}

pxml ()
{
    xmllint --pretty 1 -
}

declare -fx pjson pxml

ssh_dropall () 
{ 
    kill -9 $(ps -ef|grep "ssh ${1:?provide user}@"|awk '{print $2}') 2> /dev/null
}
